//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dinamica.erp.wcf.arm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artículos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artículos()
        {
            this.Imágenes = new HashSet<Imágenes>();
        }
    
        public int id { get; set; }
        public string Título { get; set; }
        public string Descripción_corta { get; set; }
        public string Descripción_completa { get; set; }
        public Nullable<int> Subcategoría { get; set; }
        public Nullable<bool> Publicado { get; set; }
        public byte[] Imagen_Principal { get; set; }
        public Nullable<bool> En_Stock { get; set; }
        public Nullable<bool> Destacado { get; set; }
        public decimal Precio_Base { get; set; }
    
        public virtual Subcategoría Subcategoría1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imágenes> Imágenes { get; set; }
    }
}
