//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dinamica.erp.wcf.arm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPosts
    {
        public int id { get; set; }
        public string Título { get; set; }
        public string PrimerParrafo { get; set; }
        public string Contenido { get; set; }
        public byte[] Imagen { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
