//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dinamica.erp.wcf.arm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formas_de_pago
    {
        public int id { get; set; }
        public int Empresa_de_pagos { get; set; }
        public int Cantidad_de_cuotas { get; set; }
        public int Interés { get; set; }
    
        public virtual Empresas_De_Pago Empresas_De_Pago { get; set; }
    }
}
