//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dinamica.erp.wcf.arm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElediEntities : DbContext
    {
        public ElediEntities()
            : base("name=ElediEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artículos> Artículos { get; set; }
        public virtual DbSet<Banners> Banners { get; set; }
        public virtual DbSet<BlogPosts> BlogPosts { get; set; }
        public virtual DbSet<Categorías> Categorías { get; set; }
        public virtual DbSet<Empresas_De_Pago> Empresas_De_Pago { get; set; }
        public virtual DbSet<Formas_de_pago> Formas_de_pago { get; set; }
        public virtual DbSet<Imágenes> Imágenes { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Subcategoría> Subcategoría { get; set; }
    }
}
